### ISSUE TITLE
nuget.org release

### ISSUE THREAD

**Issue by kle-sd** [cockroachdb/efcore.pg.cockroach#5]
Greetings! Was very happy to see this being developed. I found my way from this thread: https://github.com/npgsql/efcore.pg/issues/3114

I'm curious if there are any tentative schedules for a release to nuget.org?

Thank you!

**Comment by dikshant** [comment]
A Nuget release is planned! We are putting finishing touches and should be up in a few days!

**Comment by dikshant** [comment]
This is now released!
https://www.nuget.org/packages/CockroachDB.EFCore.Provider
